import React, { useState, useCallback } from 'react';
import {
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Button,
  TextField,
  FormControlLabel,
  Checkbox,
  Typography,
  Slider,
  Box,
  Stack
} from '@mui/material';
import { DualImageUploader } from './DualImageUploader';
import { Icon } from 'src/types';
import { generateId } from 'src/utils';
import { removeFileExtension, generateUniqueName } from 'src/utils/imageProcessing';

export interface ImportIconDialogProps {
  open: boolean;
  onClose: () => void;
  onImport: (icon: Icon) => void;
  existingIconNames: string[];
}

export const ImportIconDialog: React.FC<ImportIconDialogProps> = ({
  open,
  onClose,
  onImport,
  existingIconNames
}) => {
  const [iconName, setIconName] = useState('');
  const [urlIsometric, setUrlIsometric] = useState<string | null>(null);
  const [url2D, setUrl2D] = useState<string | null>(null);
  const [scale, setScale] = useState(100);
  const [isIsometric, setIsIsometric] = useState(true);
  const [autoGeneratedName, setAutoGeneratedName] = useState(true);

  // Reset form when dialog closes
  const handleClose = useCallback(() => {
    setIconName('');
    setUrlIsometric(null);
    setUrl2D(null);
    setScale(100);
    setIsIsometric(true);
    setAutoGeneratedName(true);
    onClose();
  }, [onClose]);

  // Auto-generate name from first uploaded file
  const handleIsometricChange = useCallback((url: string | null) => {
    setUrlIsometric(url);

    // If this is the first image and name is auto-generated, update the name
    if (url && autoGeneratedName && !iconName) {
      // Extract filename from data URL if possible, otherwise use generic name
      const genericName = 'Imported Icon';
      setIconName(genericName);
    }
  }, [autoGeneratedName, iconName]);

  const handleNameChange = useCallback((value: string) => {
    setIconName(value);
    setAutoGeneratedName(false);
  }, []);

  const handleImport = useCallback(() => {
    if (!urlIsometric) return;

    // Generate unique name if needed
    const existingNamesSet = new Set(existingIconNames.map(n => n.toLowerCase()));
    const baseName = iconName.trim() || 'Imported Icon';
    const finalName = generateUniqueName(baseName, existingNamesSet);

    const newIcon: Icon = {
      id: generateId(),
      name: finalName,
      url: urlIsometric,
      url2D: url2D || undefined,
      collection: 'imported',
      isIsometric,
      scale: scale / 100, // Convert percentage to decimal
      scale2D: scale / 100 // Use same scale for both views initially
    };

    onImport(newIcon);
    handleClose();
  }, [urlIsometric, url2D, iconName, scale, isIsometric, existingIconNames, onImport, handleClose]);

  const canImport = !!urlIsometric && iconName.trim().length > 0;

  return (
    <Dialog
      open={open}
      onClose={handleClose}
      maxWidth="md"
      fullWidth
      PaperProps={{
        sx: { minHeight: '60vh' }
      }}
    >
      <DialogTitle>Import Icon</DialogTitle>

      <DialogContent>
        <Stack spacing={3} sx={{ mt: 1 }}>
          {/* Name Input */}
          <TextField
            label="Icon Name"
            value={iconName}
            onChange={(e) => handleNameChange(e.target.value)}
            fullWidth
            required
            helperText="A unique name for this icon"
            autoFocus
          />

          {/* Dual Image Uploader */}
          <Box>
            <DualImageUploader
              urlIsometric={urlIsometric}
              url2D={url2D}
              onIsometricChange={handleIsometricChange}
              on2DChange={setUrl2D}
              scale={scale}
            />
          </Box>

          {/* Scale Slider */}
          <Box>
            <Typography variant="body2" gutterBottom>
              Icon Scale: {scale}%
            </Typography>
            <Slider
              value={scale}
              onChange={(_, value) => setScale(value as number)}
              min={10}
              max={300}
              step={5}
              marks={[
                { value: 10, label: '10%' },
                { value: 100, label: '100%' },
                { value: 300, label: '300%' }
              ]}
              valueLabelDisplay="auto"
            />
            <Typography variant="caption" color="text.secondary">
              Adjust how large the icon appears in the diagram
            </Typography>
          </Box>

          {/* Isometric Transform Checkbox */}
          <FormControlLabel
            control={
              <Checkbox
                checked={isIsometric}
                onChange={(e) => setIsIsometric(e.target.checked)}
              />
            }
            label={
              <Box>
                <Typography variant="body2">
                  Apply isometric transform
                </Typography>
                <Typography variant="caption" color="text.secondary">
                  Check this for 3D/isometric icons. Uncheck for flat icons (logos, UI elements).
                </Typography>
              </Box>
            }
          />
        </Stack>
      </DialogContent>

      <DialogActions>
        <Button onClick={handleClose}>Cancel</Button>
        <Button
          onClick={handleImport}
          variant="contained"
          disabled={!canImport}
        >
          Import Icon
        </Button>
      </DialogActions>
    </Dialog>
  );
};
